### ISSUE TITLE
A vimeo `background` option would be great.

### ISSUE THREAD

**Issue by patrickwc** [luwes/vimeo-video-element#43]
We have most options which you can pass as query strings in a vimeo iframe URL but no the `background=1` option. This would be a great addition, particularly for this reason: https://stackoverflow.com/a/57084804/1134053 if you have multiple background videos on a page, only 1 will autoplay if it is not set to background=1.

Thanks for a great vimeo-video-element!

**Comment by luwes** [comment]
thanks for the feedback, I opted to make `autopause=false` by default. it's more how a native video element behaves and fixes your use case. if you like to enabled the automatic pausing again just add a `autopause` attribute to the element.
